### ISSUE TITLE
Support RDS Aurora

### ISSUE THREAD

**Issue by ighanim** [aws-samples/amazon-rds-auto-restart-protection#1]
RDS Aurora is not yet supported for automatic shutdown, only RDS.

**Comment by samadncsgit** [comment]
Do you know any other way to implement Automatic shutdown for RDS Aurora if its restarted after 7 days.

**Comment by ighanim** [comment]
Hey @samadncsgit  If I got this correctly, you would like the solution to support Aurora and not just RDS. This is on the roadmap and shouldn't be a big of a change. The feature should be available by Jan 2022. Hope that meets your expectation.

**Comment by ighanim** [comment]
@samadncsgit - this is now merged and ready for use. Keen to hear your feedback.
